name: Tests

on:
  push:
    branches:
      - main
      - development
      - 'feature/**'
  pull_request:
    branches:
      - main
      - development
      - 'feature/**'

jobs:
  php-tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, ctype, json, tokenizer
          coverage: xdebug
          tools: composer

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}
          restore-keys: |
            composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Copy .env and set application key
        run: |
          cp .env.example .env || true
          php -r "file_exists('.env') || copy('.env.example', '.env');"
          php artisan key:generate || true

      - name: Run test suite
        run: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml

      - name: Upload coverage report
        if: success() && always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
          if-no-files-found: ignore
